fixed avatar styles
mywebdevru/purple pull request #187
Opened 2020-09-20 21:09 UTC by moskvichev

2020-09-21 04:54 UTC, Russkazkin requested changes

2020-09-21 04:54 UTC, Russkazkin commented on resources/sass/components/_body.scss
> +    src: url("../../assets/fonts/fa-regular-400.eot?#iefix") format("embedded-opentype"), url("../../assets/fonts/fa-regular-400.woff2") format("woff2"), url("../../assets/fonts/fa-regular-400.woff")
Чего псевдонимы то не используешь?

2020-09-21 04:54 UTC, Russkazkin commented on resources/sass/components/_body.scss
> +    src: url("../../assets/fonts/fa-solid-900.eot?#iefix") format("embedded-opentype"), url("../../assets/fonts/fa-solid-900.woff2") format("woff2"), url("../../assets/fonts/fa-solid-900.woff") forma
Здесь тоже нужен alias

2020-09-21 18:50 UTC, moskvichev commented on resources/sass/components/_body.scss
> +    src: url("../../assets/fonts/fa-regular-400.eot?#iefix") format("embedded-opentype"), url("../../assets/fonts/fa-regular-400.woff2") format("woff2"), url("../../assets/fonts/fa-regular-400.woff")
Поправил

2020-09-21 18:50 UTC, moskvichev commented on resources/sass/components/_body.scss
> +    src: url("../../assets/fonts/fa-solid-900.eot?#iefix") format("embedded-opentype"), url("../../assets/fonts/fa-solid-900.woff2") format("woff2"), url("../../assets/fonts/fa-solid-900.woff") forma
Поправил

2020-09-22 02:15 UTC, Russkazkin approved these changes

2020-09-22 02:16 UTC, merged