Все для редактирования данных пользователя 2
mywebdevru/purple pull request #85
Opened 2020-08-04 20:52 UTC by x3mart

2020-08-04 22:39 UTC, Russkazkin requested changes
В общем, есть вопросы. Пока не применяю.

2020-08-04 22:39 UTC, Russkazkin commented on app/Http/Controllers/User/ProfileController.php
>          }
Почему этот остался?

2020-08-04 22:39 UTC, Russkazkin commented on routes/web.php
> +Route::post('summernote/destroy', [SummernoteController::class, 'destroy'])->name('summernote.destroy');
Зачем? И чего тогда  js-скрипт не исправил? Или не предупредил?

2020-08-04 22:39 UTC, Russkazkin commented on routes/web.php
> +    Route::delete('edit/friends/{friend}', 'FriendsController@destroy')->name('friends.destroy');
У тебя же ресурсные контроллеры. Зачем отдельные роуты?

2020-08-04 23:21 UTC, x3mart commented on routes/web.php
> +    Route::delete('edit/friends/{friend}', 'FriendsController@destroy')->name('friends.destroy');
не совсем. для едит должно быть '{user}/edit/vehicles' в ресурсе не так

2020-08-04 23:23 UTC, x3mart commented on app/Http/Controllers/User/ProfileController.php
>          }
оставил. Пока не придумал, как с ним быть. Он не первостепенный. потом обсудим.

2020-08-04 23:23 UTC, x3mart commented on routes/web.php
> +Route::post('summernote/destroy', [SummernoteController::class, 'destroy'])->name('summernote.destroy');
Это ошибка

2020-08-04 23:43 UTC, Russkazkin commented on routes/web.php
> +    Route::delete('edit/friends/{friend}', 'FriendsController@destroy')->name('friends.destroy');
у тебя имя ресурса будет vehicles, то есть по идее путь должен быть /user/vehicles/{user}/edit, ну или типа того. Ты не пробовал?

2020-08-05 00:06 UTC, Russkazkin commented on routes/web.php
> +    Route::delete('edit/friends/{friend}', 'FriendsController@destroy')->name('friends.destroy');
Нет, не получается. Попробовал. Ок

2020-08-05 00:11 UTC, Russkazkin approved these changes

2020-08-05 00:11 UTC, merged

2020-08-05 00:14 UTC, x3mart commented on app/Http/Controllers/User/ProfileController.php
>          }
Согласен